export default function Head({ params }: {
  params: {
    slug: string
  }
}) {
  return (
    <>
      {/* TODO - can't we use params.slug here? */}
      <title>{params.slug} | OpenTable Clone</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
